config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
      confirmations: "users/confirmations",
      omniauth: "users/omniauth",
      passwords: "users/passwords",
      registrations: "users/registrations",
      sessions: "users/sessions",
      unlocks: "users/unlocks"
  }

  root to: "homepage#index"

  get    "dashboard",     to: "dashboard#index"
  get    "dashboard/*id", to: "dashboard#index"
  post   "dashboard",     action:"create",  controller:"dashboard"
  delete "dashboard/*id", action:"destroy", controller:"dashboard"
  resources :dashboard, only: [ :index, :create, :delete ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  after_action :set_csrf_cookie

  # Allows cookies with csrf token to post delete update
  def set_csrf_cookie
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  # Used to direct users to dashboard after login
  def stored_location_for(resource)
    nil
  end

  # Used to direct users to dashboard after login
  def after_sign_in_path_for(resource)
    '/dashboard'
  end

  protected
  # Needed to configure the additional parameters for devise users
  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_footer.html.erb
<footer class="body-footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
      </div>
      <div class="col-xs-9">
      </div>
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <div class="container">
    <% if user_signed_in? %>
        <%= link_to 'Predikto', dashboard_path, class: 'navbar-brand' %>
    <% else %>
        <%= link_to 'Predikto', root_path, class: 'navbar-brand' %>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav ml-auto" id="header-lists">
        <% if user_signed_in? %>
            <li>
              <%= link_to "Account", edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "Log Out", destroy_user_session_path %>
            </li>
        <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path %>
            </li>
            <li><%= link_to "Log In", new_user_session_path %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>